import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import NavBar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { useSession } from "next-auth/react";
import logo2 from "/public/logo2.svg";
import LoginButton from "@/components/LoginButton";
import CreateListingButton from "@/components/CreateListingButton";
export default function Home() {

  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png"/>
      </Head>
      <NavBar/>
      <main className="w-screen h-screen bg-primary">
        <div className="flex items-center justify-center w-screen h-screen bg-primary">
          <div className="m-2"><img className="scale-125 pb-16" src="/logo2.svg"></img></div>
        </div>
        <div className=" h-screen bg-red-500">
        <div className=" w-screen h-full flex justify-center items-center">
        <CreateListingButton/>
        </div>
        </div>
      </main>
    </>
  );
}
